package IR;
import java.util.*;
import TEMP.*;

public class IRcommand_Jump_If_Eq_To_Zero extends IRcommand {
	
	TEMP t;
	String label_name;
	int lineNumber;
	
	public IRcommand_Jump_If_Eq_To_Zero(TEMP t, String label_name,int line)
	{
		this.t          = t;
		this.label_name = label_name;
		this.lineNumber = line;
	}

	/**
	 * Generates a set of variables generated by this command.
	 * 
	 * @return An empty set as no variables are used in this command.
	 */
	public Set<String> genVars() {
		return new HashSet<>();
	}

	/**
	 * Generates a set of variables killed by this command.
	 * 
	 * @return An empty set as no variables are killed in this command.
	 */
	public Set<String> killVars(int maxLine) {
		return new HashSet<>();
	}

	public void printIR() {
		System.out.println("if (" + t.toString() + " == 0) goto " + label_name);
	}
}
