package IR;
import java.util.*;

public class IRcommand_Label extends IRcommand {

	String label_name;
	int lineNumber;
	boolean isScopeStart;
	
	public IRcommand_Label(String label_name,int line,boolean isScopeStart)
	{
		this.label_name = label_name;
		this.lineNumber = line;
		this.isScopeStart = isScopeStart;
	}

	/**
	 * Generates a set of variables generated by this command.
	 * 
	 * @return An empty set as no variables are used in this command.
	 */
	public Set<String> genVars() {
		return new HashSet<>();
	}

	/**
	 * Generates a set of variables killed by this command.
	 * 
	 * @return An empty set as no variables are killed in this command.
	 */
	public Set<String> killVars(int maxLine) {
		return new HashSet<>();
	}

	public void printIR() {
		System.out.println(label_name + ":");
	}
}
