package IR;
import java.util.*;

public class IRcommand_Jump_Label extends IRcommand {

	String label_name;
	int lineNumber;
	
	public IRcommand_Jump_Label(String label_name,int line) {
		this.label_name = label_name;
		this.lineNumber = line;
	}
	
	/**
	 * Generates a set of variables generated by this command.
	 * 
	 * @return An empty set as no variables are used in this command.
	 */
	public Set<String> genVars() {
		return new HashSet<>();
	}

	/**
	 * Generates a set of variables killed by this command.
	 * 
	 * @return An empty set as no variables are killed in this command.
	 */
	public Set<String> killVars(int maxLine) {
		return new HashSet<>();
	}

	public void printIR() {
		System.out.println("goto " + label_name);
	}
}
