package IR;
import java.util.*;
import TEMP.*;

public class IRcommand_Return extends IRcommand {

    public TEMP return_value;
    int lineNumber;
    
    public IRcommand_Return(TEMP return_value,int line) {
        this.return_value = return_value;
        this.lineNumber = line;
    }

    /**
     * Generates a set of variables generated by this command.
     * 
     * @return An empty set as no variables are generated in return commands.
     */
    public Set<String> genVars() {
		return new HashSet<>();
	}

    /**
     * Generates a set of variables killed by this command.
     * 
     * @return An empty set as no variables are killed in return commands.
     */
	public Set<String> killVars(int maxLine) {
		return new HashSet<>();
	}

    public void printIR() {
        System.out.println("return " + return_value.toString());
    }

}
