package IR;
import java.util.*;
import TEMP.*;

public class IRcommandConstInt extends IRcommand {
	
	TEMP t;
	int value;
	int lineNumber;
	String tLabeled;
	
	public IRcommandConstInt(TEMP t,int value,int line) {
		this.lineNumber = line;
		this.t = t;
		this.value = value;
		this.tLabeled = t.toString()+";"+line;
	}

	/**
	 * Generates a set of variables generated by this command.
	 * 
	 * @return A set containing the variable t.
	 */
	public Set<String> genVars() {
		return new HashSet<>(Arrays.asList(tLabeled));
	}

	/**
	 * Generates a set of variables killed by this command.
	 * 
	 * @return A set containing the variable t as a string.
	 */
	public Set<String> killVars(int maxLine) {
		List<String> arr = new ArrayList<>();
		for (int j = 0; j < maxLine; j++) {
			if (j != this.lineNumber) {
				arr.add(t.toString()+";"+j);
			}
		}
		arr.add(t.toString()+";?");
		return new HashSet<>(arr);
	}

	public void printIR() {
		System.out.println(t.toString() + " := " + String.format("%d", value));
	}
}
